minor changes to recursion approach

diff --git a/kubectl-build b/kubectl-build
--- a/kubectl-build
+++ b/kubectl-build
@@ -11,9 +11,8 @@ for d in jq spruce kubectl python envsubst; do which "$d" >/dev/null || {
   exit 1
 }; done
 
-
 # Configure the manifest file we'll be looking for.
-ASSEMBLY_FILE="assemble.yml"
+ASSEMBLY_FILE="assembly.yml"
 
 # Help...
 if [[ $# -eq 0 ]]; then
@@ -26,7 +25,7 @@ resources:                           # resources specify yaml files to combine
                                      # into a single yaml output stream.
 - path/to/file.yml                   # explicitly include a file
 - path/to/bare/directory             # collect all yml files within
-- path/to/assemble/directory         # when ${ASSEMBLY_FILE} in root, process it
+- path/to/assembly/directory         # when ${ASSEMBLY_FILE} in root, process it
 
 vars:                                # vars specify variables that can be
                                      # overridden by environment variables.
@@ -40,53 +39,59 @@ patches:                             # patches specify "indirect" modifications
                                      # to resources included in this file
 - target:                            # start patch, every resource included will be compared
     kind: Service                    # against the keys under the target. target must be
-    metadata:                        # specified fully enough to match eactly one manifest.
+    metadata:                        # specified fully enough to match exactly one manifest.
       name: my-service               # any keys/values can be used for matching.
   replacements:                      # start list of changes to make to manifest
-  - path: spec.virtualhost.fqdn      # a json path string that points to the
-                                     # field to modify
+  - path: spec.virtualhost.fqdn      # json path pointing to the field to modify
     value: service.\${CLUSTER_HOST}   # the value to insert
 EOF
 fi
 
-# Assemble collects yaml manifests enumerated in an "assembly" file, applies
+# Assembly collects yaml manifests enumerated in an "assembly" file, applies
 # patches defined within and streams the modified results to standard out.
-function assemble() {
+function assembly() {
   # Save the directory that was used when this was invoked.
   local root=${1}
   # Save a path to the config file that may exist in the supplied directory.
   local configFile=${root}/${ASSEMBLY_FILE}
   # Attempt to read the configuration file. If it doesn't exist, this fails with
   # a clear error message.
-  local config=$(spruce json < ${configFile})
-  # Attempt to load environment variables so configFile can be re-parsed to
-  # replace them.
-  local vars=$(echo "${config}" | jq -cr '.vars[]')
-  if [[ "${vars}" != "" ]]; then
-    # Iterate through each variable, setting it if it isn't already provided in
-    # the environment.
-    for var in ${vars}; do
-      name=$(jq -r '.name' <<<"${var}")
-      # This insane garbage determines if the variable is set in the environment
-      # already.
-      if ! compgen -e -X "!$name" > /dev/null; then
-        # if it is not, first, try to get the value from an external file
-        valueFromFile=$(jq -rc '.valueFromFile' <<<"${var}")
-        if [[ "${valueFromFile}" != "null" ]]; then
-          value=$(cat ${root}/${valueFromFile})
+  local config=$(
+    # Do variable substitutions in a subshell so vars in one assembly do not
+    # affect nested assemblys.
+    local rawConfig=$(spruce json <${configFile})
+    # Attempt to load vars so configFile can be re-parsed to replace them.
+    local vars=$(echo "${rawConfig}" | jq -cr '.vars[]')
+    if [[ "${vars}" != "" ]]; then
+      # Iterate through each variable, setting if it isn't already provided in
+      # the environment.
+      for var in ${vars}; do
+        # Extract variable name.
+        local name=$(jq -r '.name' <<<"${var}")
+        # This insane garbage determines if the variable is set in the
+        # environment already.
+        if ! compgen -e -X "!$name" >/dev/null; then
+          # If var is not set in environment, try to get the value from an
+          # external file
+          valueFromFile=$(jq -rc '.valueFromFile' <<<"${var}")
+          if [[ "${valueFromFile}" != "null" ]]; then
+            # Absent files will cause failures.
+            value=$(cat ${root}/${valueFromFile})
+          fi
+          # If value hasn't been set yet, try to get it from inline declaration.
+          if [[ "${value:-}" == "" ]]; then
+            value=$(jq -re '.value' <<<"${var}")
+          fi
+          # Export value so envsubst will see it.
+          eval export ${name}="${value}" >/dev/null
         fi
-        if [[ "${value:-}" == "" ]]; then
-          value=$(jq -r '.value' <<<"${var}")
-        fi
-        eval export ${name}="${value}" > /dev/null
-      fi
-    done
-    config=$(envsubst <<<"${config}")
-  fi
+      done
+    fi
+    # Rebuild config using supplied environment variables.
+    envsubst <<<"${rawConfig}"
+  )
   # Save the resources enumerated in the assembly file, one per line.
   local resources=$(echo "${config}" | jq -cre '.resources[]')
-  # Save the patches enumerated in the assembly file, one per line.
-  local patches=$(echo "${config}" | jq -cr '.patches[]' 2>/dev/null)
   # Read all specified resources.
   manifests=$(
     cd ${root}
@@ -95,20 +100,18 @@ function assemble() {
         # If a resource points to a directory that contains an assembly file,
         # run assembly on it and collect the output. This is recursive and can
         # be nested as deeply as needed.
-        assemble "${root}/${item}"
+        assembly "${root}/${item}"
       else
         # If the resource pointed to does not contain an assembly file, collect
         # the raw file pointed to or, in the case of a directory, every file
-        # that has a .yml extension.
+        # within that has a .yml extension.
         collect "${root}/${item}"
       fi
     done
   )
-  if [[ "${patches}" == "" ]]; then
-    # If the assembly file does not specify any patches, output all collected
-    # manifests immediately.
-    echo "${manifests}"
-  else
+  # Save the patches enumerated in the assembly file, one per line.
+  local patches=$(echo "${config}" | jq -cr '.patches[]' 2>/dev/null)
+  if [[ "${patches}" != "" ]]; then
     # Iterate through each patch, applying it to the desired target.
     for patch in ${patches}; do
       # Collect the target for the patch, this will be used to filter manifests
@@ -127,22 +130,20 @@ function assemble() {
       fi
       # Produce a JQ expression that can apply the replacements.
       replacements=$(echo "${patch}" | jq -r '.replacements | map("."+(.path)+" = "+(.value|tojson)) | join(" | ")')
-      # Overwrite the manifest listing with the matched/modified manifests and
-      # all unmatched manifests. The next loop through will do the same.
+      # Overwrite the manifest listing with modifications supplied, the next
+      # loop through will do the same.
       manifests=$(
+        # Output any manifest that didn't match.
         echo "${manifests}" | jq -c 'select(contains('${filter}') | not)'
+        # Output matched manifest with replacements applied.
         echo "${matched}" | jq -c ". | ${replacements}"
       )
     done
-    # When work is complete, convert manifests back to yaml for ease of reading.
-    for manifest in ${manifests}; do
-      json2yaml <<<"${manifest}"
-      echo "---"
-    done
   fi
+  echo "${manifests}"
 }
 
-# collect takes he path to a file or a directory and produces jsonl output, one
+# collect takes the path to a file or a directory and produces jsonl output, one
 # line for each manifest referenced.
 function collect() {
   local target=${1}
@@ -169,11 +170,14 @@ function expand() {
 }
 
 # json2yaml converts json back to yaml.
-function json2yaml {
-  python -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read())))'
+function json2yaml() {
+  python -c 'import sys, yaml, json; print(yaml.dump(json.loads(sys.stdin.read())).rstrip())'
 }
 
-# Try to run assemble on every provided path.
+# Try to run assembly on every provided path.
 for dir in $*; do
-  assemble ${PWD}/${dir}
+  while read -r manifest; do
+     json2yaml <<<"${manifest}"
+     echo "---"
+  done <<<"$(assembly ${PWD}/${dir})"
 done
